language: shell
os: linux

_defaults: &defaults
  cache: false
  services:
    - docker
  before_install:
    - scripts/travis/run-docker.sh
  install:
    - mkdir -p bin && ./bpf-sdk-install.sh bin
  before_cache:
    - scripts/travis/stop-docker.sh

_localnet: &localnet
  language: node_js
  node_js:
    - 14
  before_script:
    - npm install -g @solana/web3.js
    - npx solana-localnet update
    - npx solana-localnet up

jobs:
  include:
    - <<: *defaults
      name: Dex unit tests
      script:
        - docker exec dev ./do.sh test dex
    - <<: *defaults
      name: Dex integration tests
      <<: *localnet
      script:
        - docker exec dev ./scripts/travis/dex-tests.sh
    - <<: *defaults
      name: Lockup tests
      <<: *localnet
      script:
        - docker exec dev make -C lockup init-test features=strict

# Disabled because these tests require the shared memory program in the validator genesis,
# which currently requires a custom local setup.
#
#    - <<: *defaults
#      name: Registry tests
#      <<: *localnet
#      script:
#        - docker exec dev make -C registry init-test
    - <<: *defaults
      name: Fmt and Common Tests
      script:
        - docker exec dev cargo build
        - docker exec dev cargo fmt -- --check
        - docker exec -w=/workdir/common dev cargo test --features client,strict
