[package]
name = "serum-pool-schema"
version = "0.1.0"
authors = ["Sebastian Conybeare <sebastian@projectserum.com>"]
edition = "2018"

[features]
program = []
default = []

[dependencies]
borsh = { git = "https://github.com/project-serum/borsh", branch = "serum" }
solana-program = "1.4.14"

[[bin]]
name = "print-schema"
path = "src/print-schema.rs"
