[package]
name = "codegen"
version = "0.1.0"
authors = ["armaniferrante <armaniferrante@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
proc-quote = "0.2"
syn = { version = "0.15", features = ["full", "extra-traits"] }
heck = "0.3.1"
