[package]
name = "serum-pool-simple"
version = "0.1.0"
description = "Simple serum pool"
edition = "2018"

[features]
no-entrypoint = []
program = []
default = []

[dependencies]
solana-program = "1.4.14"
serum-pool = { version = "0.1.0", path = "../..", default-features = false }

[lib]
name = "serum_pool_examples_simple"
crate-type = ["cdylib", "lib"]
